### ISSUE TITLE
Add protobuf transformer

### ISSUE THREAD

**Issue by gregLibert** [massalabs/as#108]
The idea is for an end user to be able to write function such as:

```typescript
@exportAs("SayHello")
function _sayHello(language: string, name: string): string {
  let salute = 'Hello'; + language;
  
  if (language == "french") {
    salute = "Bonjour";
  }

  return `${salut}, ${name}!`;
}
```

And that the transformer :

- [ ] create the proto file - #109 
- [ ] generate helpers - #164 
- [ ] create the wrapping function `SayHello` - #114  
- [ ] replace the SC with the updated one and load all dependencies - #132
