### ISSUE TITLE
Update Library for Release-Ready

### ISSUE THREAD

**Issue by Ben-Rey** [massalabs/as#110]
# Objective
The purpose of this issue is to ensure that the library is updated to meet the expected criteria for an application to be maintained and considered release-ready. The requirements are outlined in the Run team procedure: [Definition of Release-Ready](https://www.notion.so/massa-innoteam/Definition-of-Release-Ready-964a4f2ffd9549129edf76d6c623c490).

# Tasks
This issue is a meta issue. Please create additional issues to perform the task and reference them. Keep in mind that the issues should be as short as possible to improve overall efficiency.
**Feel free to break tasks down into smaller tasks**

## Testing

- [ ] Include test coverage
- [ ] Improve test coverage if necessary
- [ ] Add a test coverage badge to the README file
- [ ] Divide tests into different categories: black/white box, code sample tests if possible

## Documentation

- [ ] Enhance or add to Git documentation: readme, installation, contribute, license, and powered by.
- [ ] Enhance or add to code documentation: classes, functions, etc.
- [ ] Enhance or add to Massa Read the Docs

## Security

- [ ]  Define a security model
- [ ]  Implement proper countermeasures, such as static analysis of code and security checks of dependencies

## Automation

- [ ]  Automate tasks that can be automated

## Wrap Up

- [ ]  Ensure that the Run team procedure was properly applied and update the document if necessary
- [ ]  Communicate that the library is now considered release-ready
