### ISSUE TITLE
Update Library for Release-Ready

### ISSUE THREAD

**Issue by Ben-Rey** [massalabs/as#111]
# Objective

The purpose of this issue is to ensure that the library is updated to meet the expected criteria for an application to be maintained and considered release-ready. The requirements are outlined in the Run team procedure: [Definition of Release-Ready](https://www.notion.so/massa-innoteam/Definition-of-Release-Ready-964a4f2ffd9549129edf76d6c623c490).

# Tasks

This issue is a meta issue. Please create additional issues to perform the task and reference them. Keep in mind that the issues should be as short as possible to improve overall efficiency.
**Feel free to break tasks down into smaller subtasks. For each new subtask, you can create a checkbox to track our work** 

## Testing

- [x] #112
- [x] Improve test coverage if necessary (Issue can be split by package: as-proba, as-transformer, as-types)
- [x] Add a test coverage badge to the README file
- [x] #198
- [ ] Divide tests into different categories: black/white box, code sample tests if possible (Issue can be split by package: as-proba, as-transformer, as-types)

## Documentation

- [x] #151
- [x] Enhance or add to Massa Read the Docs

### Git Documentation
- [x] #119
- [x] #120
- [x] #121

### Code Documentation
- [x] #115 
- [x] #116
- [x] #117

## Security

- [ ]  Define a security model
- [x]  Implement proper countermeasures, such as static analysis of code and security checks of dependencies

## Automation

- [x]  Automate tasks that can be automated

## Wrap Up

- [ ]  Ensure that the Run team procedure was properly applied and update the document if necessary
- [ ]  Communicate that the library is now considered release-ready

**Comment by Ben-Rey** [comment]
@gregLibert We can close this issue. It seems to be over

**Comment by Ben-Rey** [comment]
@gregLibert Can we close this one ?
I can add a specific one for security
