### ISSUE TITLE
Clean as

### ISSUE THREAD

**Issue by gregLibert** [massalabs/as#205]
- [x] #217
- [x] #223
- [x] #227
- [x] #219 (will be done when new npm version released)
- [x] #224
- [x] Improve issue template (ture also for massa-as-sdk I think)

type:
- [x] #206
- [x] #211
- [x] don't lose time on args
- [x] #215
- [x] #208

For SafeMath: see also comments here https://github.com/massalabs/as/pull/101

transfromer:
- [x] #189 
- [x] #225
- [x] #234

proba:
- [x] #213
- [x] #229
if not possible, find a way to deactivate it and explain when to test it https://github.com/massalabs/as/blob/main/packages/as-proba/assembly/__tests__/binomial.spec.ts#L30

Must have:
- [x] #91

**Comment by gregLibert** [comment]
cc @Ben-Rey

**Comment by Thykof** [comment]
>  remove fromArgs, addArgs and to toArgs on all objects (@Thykof can you confirm ?)

Yes, I confirm, because now we can add any Serializable object.

**Comment by 0xSwapFeeder** [comment]
@Thykof so now instead of implementing random unsafe methods, we should inherit the classes from Serializable interface right ?

**Comment by 0xSwapFeeder** [comment]
@gregLibert not sure what you refer to when talking about documenting transformer, you meant MassaExport transformer ?
